name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: Setup Machine
        run: sudo apt-get update && sudo apt-get upgrade
      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
      - name: Compile All
        run: make compile-all
      - name: Run Tests
        run: make test-all
      - name: Make Book
        run: make book
      - name: Commit Book
        run: |
          git add book.pdf
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update book.pdf"
          git push
