name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: Install pdflatex
        run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
      - name: List Content
        run: ls
      - name: Compile All
        run: make compile-all
      - name: Run Tests
        run: make test-all
      - name: Make Book
        run: make book
